# Generated by ormin_importer. DO NOT EDIT.

type
  Attr = object
    name: string
    tabIndex: int
    typ: DbTypekind
    key: int   # 0 nothing special,
               # +1 -- primary key
               # -N -- references attribute N
const tableNames = [
  "ipe"
]

const attributes = [
  Attr(name: "id", tabIndex: 0, typ: dbInt, key: 1),
  Attr(name: "name", tabIndex: 0, typ: dbVarchar, key: 0),
  Attr(name: "h", tabIndex: 0, typ: dbFloat, key: 0),
  Attr(name: "b", tabIndex: 0, typ: dbFloat, key: 0),
  Attr(name: "tw", tabIndex: 0, typ: dbFloat, key: 0),
  Attr(name: "tf", tabIndex: 0, typ: dbFloat, key: 0),
  Attr(name: "r", tabIndex: 0, typ: dbFloat, key: 0),
  Attr(name: "area", tabIndex: 0, typ: dbFloat, key: 0),
  Attr(name: "weight", tabIndex: 0, typ: dbFloat, key: 0)
]
